services:
  - type: web
    name: telegram-bot-server
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: TOKEN
        value: "7706875882:AAH5o7WQFV1mxLpt6TikdploTOr966dala8"
      - key: CHAT_ID
        value: "7689242465"
    autoDeploy: true
